2013-07-18 14:28:35.317 [error] <0.92.0> CRASH REPORT Process <0.92.0> with 0 neighbours exited with reason: bad argument in call to io:format(<0.81.0>, "in ofdp_recv init Pid = ~p~n", <0.92.0>) in loom_ofdp_recv:init/1 line 61 in gen_server:init_it/6 line 328
2013-07-18 14:28:35.323 [error] <0.88.0> Supervisor loom_ofdp_recv_sup had child loom_ofdp_recv started with {loom_ofdp_recv,start_link,undefined} at <0.92.0> exit with reason bad argument in call to io:format(<0.81.0>, "in ofdp_recv init Pid = ~p~n", <0.92.0>) in loom_ofdp_recv:init/1 line 61 in context child_terminated
